;;; early-init.el --- Early initialization. -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:

(when (or (featurep 'esup-child)
	  (daemonp)
	  noninteractive)
  (setq package-enable-at-startup nil))
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-buffer-file-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(setq locale-coding-system 'utf-8)
(setq gc-cons-percentage 1.0)
(setq gc-cons-threshold most-positive-fixnum)
(setq inhibit-startup-message t)
(setq load-prefer-newer noninteractive)
(setq frame-inhibit-implied-resize t)
(setq initial-major-mode 'fundamental-mode)
(setq-default bidi-display-reordering nil)
(setq bidi-inhibit-bpa t)
(setq long-line-threshold 1000)
(setq large-hscroll-threshold 1000)
(setq syntas-wholeline-max 1000)
(setq-default bidi-paragraph-direction 'left-to-right)
(setq jit-lock-defer-time 0.3)
(setq read-process-output-max (* 4 1024 1024))
(setq process-adative-read-buffering nil)
(setq native-comp-jit-compilation nil)
(push '(menu-bar-lines . 0) default-frame-alist)
(push '(tool-bar-lines . 0) default-frame-alist)
(push '(vertical-scroll-bars) default-frame-alist)
(when (featurep 'ns)
  (push '(ns-transparent-titlebar . t) default-frame-alist)
  (push '(ns-appearance . dark) default-frame-alist))
(push '(fullscreen . maximized) initial-frame-alist)
(when (featurep 'ns)
  (setq ns-command-modifier 'meta)
  (setq ns-alternate-modifier 'super))

(provide 'early-init)
;;; early-init.el ends here
